### ISSUE TITLE
React Landing Page Clone (new-pjct-react-1-landing-page-clone)

### ISSUE THREAD

**Issue by FirstLearnJava** [FirstLearnJava/pjct-next-4-final-project#6]
Implement landing page with React, CSS Modules and SCSS.

Rebuild it in React (looking at the code as little as possible).

## TODO

- [ ] Choose a landing page from [Landingfolio](https://www.landingfolio.com/)
- [ ] Copy all elements of the landing page
- [ ] Style the elements

## Stretch TODOs

- [ ] Copy animations and videos
- [ ] Copy interactive parts of the website
- [ ] Right after [creating your first (empty) Git commit](https://learn.upleveled.io/courses/bootcamp-pern/modules/cheatsheet-command-line/#4-create-and-push-an-initial-commit), create a new branch. Use this branch to [open a pull request on GitHub](https://learn.upleveled.io/courses/bootcamp-pern/modules/cheatsheet-git-github/#opening-pull-requests)

## Acceptance Criteria

- [ ] Preflight runs through without errors in your project
  - [ ] Link in your GitHub repo's About section: Netlify deployed website
- [ ] Link to original landing page in comment below
- [ ] Project has been [imported into CodeSandbox](https://learn.upleveled.io/courses/bootcamp-pern/modules/cheatsheet-tasks/#codesandbox) and a comment has been added below with the sandbox URL
- [ ] [Drone bot](https://learn.upleveled.io/courses/bootcamp-pern/modules/cheatsheet-tasks/#upleveled-drone) has been tagged and responded with a passing message
- [ ] Correct GitHub commit message format (see [Writing Commit Messages](https://learn.upleveled.io/courses/bootcamp-pern/modules/cheatsheet-git-github/#writing-commit-messages))
